name: maps_flutter
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  animate_do: ^4.2.0
  bloc: ^9.2.0
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  geolocator: ^14.0.2
  google_maps_flutter: ^2.4.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
